
language: c

python:
  - "2.7"

sudo: false

env:
  global:
    - LVA_CC_FLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs"
    - LVA_LD_FLAGS="-shared --coverage"

matrix:
  include:
    - env: LUA="lua 5.1" VARARG=vararg
      os: osx
    - env: LUA="lua 5.1" VARARG=vararg
      os: linux
    - env: LUA="lua 5.2" VARARG=vararg
      os: linux
    - env: LUA="lua 5.3" VARARG=vararg
      os: linux
    - env: LUA="lua 5.4" VARARG=vararg
      os: linux
    - env: LUA="luajit 2.0" VARARG=vararg
      os: linux
    - env: LUA="luajit 2.1" VARARG=vararg
      os: linux
    - env: LUA="lua 5.1" VARARG=vararg-lua
      os: linux
    - env: LUA="lua 5.2" VARARG=vararg-lua
      os: linux
    - env: LUA="lua 5.3" VARARG=vararg-lua
      os: linux
    - env: LUA="lua 5.4" VARARG=vararg-lua
      os: linux
    - env: LUA="luajit 2.0" VARARG=vararg-lua
      os: linux
    - env: LUA="luajit 2.1" VARARG=vararg-lua
      os: linux

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master
    - curl_mime

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:~/Library/Python/2.7/bin/; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LVA_LD_FLAGS="-bundle -undefined dynamic_lookup -all_load --coverage"; fi
  - pip2 install --user cpp-coveralls
  - pip2 install --user hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate

install:
  - luarocks make rockspecs/$VARARG-scm-0.rockspec CFLAGS="$LCURL_CC_FLAGS" LIBFLAG="$LCURL_LD_FLAGS"

before_script:
  - luarocks show luacov > /dev/null 2>&1 || luarocks install luacov

script:
  - cd test
  - lua -lluacov test.lua

after_success:
  - luarocks show luafilesystem    > /dev/null 2>&1 || luarocks install luafilesystem
  - luarocks show lua-path         > /dev/null 2>&1 || luarocks install lua-path
  - luarocks show lua-curl         > /dev/null 2>&1 || luarocks install lua-curl
  - luarocks show luacov-coveralls > /dev/null 2>&1 || luarocks install luacov-coveralls
  - if [ $VARARG = "vararg" ]; then
      cd $TRAVIS_BUILD_DIR;
      coveralls -i vararg.c;
    else
      luacov-coveralls;
    fi

notifications:
  email:
    on_success: change
    on_failure: always
