
language: c

python:
  - "2.7"

sudo: false

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1" VARARG=vararg
    - compiler: ": Lua52"
      env: LUA="lua 5.2" VARARG=vararg
    - compiler: ": Lua53"
      env: LUA="lua 5.3" VARARG=vararg
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0" VARARG=vararg
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1" VARARG=vararg
    - compiler: ": Lua51"
      env: LUA="lua 5.1" VARARG=vararg-lua
    - compiler: ": Lua52"
      env: LUA="lua 5.2" VARARG=vararg-lua
    - compiler: ": Lua53"
      env: LUA="lua 5.3" VARARG=vararg-lua
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0" VARARG=vararg-lua
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1" VARARG=vararg-lua

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - export CC=gcc
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:~/Library/Python/2.7/bin/; fi
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin
  - pip install --user cpp-coveralls

install:
  - luarocks make rockspecs/$VARARG-scm-0.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"

before_script:
  - luarocks show luafilesystem    > /dev/null 2>&1 || luarocks install luafilesystem
  - luarocks show lua-path         > /dev/null 2>&1 || luarocks install lua-path
  - luarocks show lua-curl         > /dev/null 2>&1 || luarocks install lua-curl
  - luarocks show luacov-coveralls > /dev/null 2>&1 || luarocks install luacov-coveralls

script:
  - cd test
  - lua -lluacov test.lua

after_success:
  - if [ $VARARG = "vararg" ]; then
      cd $TRAVIS_BUILD_DIR;
      coveralls -i vararg.c;
    else
      luacov-coveralls;
    fi

notifications:
  email:
    on_success: change
    on_failure: always
